---
abstract: 'An automated interface for OpenSVN.csie.org.'
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132140'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-OpenSVN
provides:
  WWW::OpenSVN:
    file: lib/WWW/OpenSVN.pm
    version: v0.1.4
  WWW::OpenSVN::Base:
    file: lib/WWW/OpenSVN.pm
  WWW::OpenSVN::Error:
    file: lib/WWW/OpenSVN.pm
requires:
  LWP::UserAgent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: http://web-cpan.berlios.de/modules/WWW-OpenSVN/
  license: http://en.wikipedia.org/wiki/MIT_License
  repository: https://bitbucket.org/shlomif/perl-www-opensvn
version: v0.1.4
